# Site settings
title: rachelslurs
email: rachelcantor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  blah
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rachelslurs.github.com" # the base hostname & protocol for your site
twitter_username: rachiecakies
github_username:  rachelslurs

# Build settings
markdown: kramdown
